### ISSUE TITLE
Cannot login after deployment

### ISSUE THREAD

**Issue by kjell-van-straaten** [illacloud/deploy-illa-manually#1]
Hi,

Just deployed Illa manually using the offical Slim image following the steps outlined in the README:

The application works, however, now I arrive on a login page which i cannot seem to bypass. Creating users is also not possible as e-mails do not get send (I haven't configured any email server so I suppose this is right). How do I fix this?

kind regards,
Kjell

![image](https://user-images.githubusercontent.com/114096214/203070001-730a0a2f-d47e-45c6-9c5e-3929d948261a.png)

**Comment by meowcat** [comment]
Same problem here

**Comment by karminski** [comment]
hi, 

Please check the builder-backend logs for more details. run the following command:
```bash
docker logs builder-backend
```

and check the connection to the https://email.illasoft.com/ (our email sender API. will return "404 page not found")
```bash
curl https://email.illasoft.com/
```

---

We will provide a bypass method as soon as possible. For the first version, we consider that our user may not have the SMTP server or could not config the SMTP server. So we provided the email sender API for the new user registration.

**Comment by kjell-van-straaten** [comment]
Hi, thank you for the reply.

Is there any documentation on how to use this API to create a new user? I would like to start with testing Illa.

Kr,
Kjell

**Comment by meowcat** [comment]
By the way, I couldn't even sign up to the [official one](https://fast-try.illacloud.com). Never got a confirmation email.

**Comment by kjell-van-straaten** [comment]
![image](https://user-images.githubusercontent.com/114096214/203491069-e994d1d6-ef64-41ba-b764-9cc25d9dfca4.png)

As seen in the image, the email sender API is reachable, but there are (I Think) no logs emitted when "send code" command is executed.

**Comment by naj1n** [comment]
@kjell-van-straaten hi, please provide the message when u click the `send code` button. Is it `Verification code sent` ? Or error message?

**Comment by kjell-van-straaten** [comment]
![image](https://user-images.githubusercontent.com/114096214/203493316-0401d69a-2646-44f3-89b4-f688fdde3510.png)
I starts counting but now it just gave this error.

**Comment by karminski** [comment]
@kjell-van-straaten 

Hi, 

It seems the network was fine, but the web page try to connect the localhost API server, and the API server was deployed on another host (or virtual machine?).

The official slim image can only run on localhost.

if you run an instance at a non-localhost environment, make sure to config the deploy-illa-manually/docker/scripts/run.sh:

```bash
# builder-backend api server serve address
API_SERVER_ADDRESS=replace_with_your_server_address

# builder-backend websocket server serve address
WEBSOCKET_SERVER_ADDRESS=replace_with_your_server_address

```

and if you do not want to build image by yourself, you can replace the last line "illa-builder:latest" with "illasoft/illa-builder:latest"

Or, just use [https://github.com/illacloud/illa](https://github.com/illacloud/illa) for auto deploy.

And please paste the browser DevTools Network tab snapshot, we will follow up quickly.

**Comment by kjell-van-straaten** [comment]
![image](https://user-images.githubusercontent.com/114096214/203720133-3fade2cf-ac15-461b-aed8-f6ba15d60222.png)
See name = verification 

![image](https://user-images.githubusercontent.com/114096214/203720497-f9a80e4f-5068-4f26-a6ba-a9d1cbb026a9.png)

It appears indeed the slim image is trying to send verification to localhost, while this is not used.

**Comment by kjell-van-straaten** [comment]
Using the docker folder and the script deploy-illa-manually/docker/scripts/run.sh (after editing the variables, using the image from repo) did work, now I logged in and can test out the environment. Thanks for the help! maybe you could add this in the central readme.md to avoid this for VM users in the future! Thanks so much for the help :).

**Comment by karminski** [comment]
@kjell-van-straaten 
Glade to hear that. And many thanks for suggestion. We added it. 👍

https://github.com/illacloud/deploy-illa-manually/blob/main/docker/README.md
