### ISSUE TITLE
root default can't login

### ISSUE THREAD

**Issue by supperman009** [illacloud/deploy-illa-manually#10]
look this! root is not email address! can't login!
用户名只能填邮箱地址，无法登录。
![image](https://user-images.githubusercontent.com/8335353/219960126-86edade1-06b9-4cb8-88bb-dabf3a93e192.png)

修改数据库后台，设置email为root@163.com 也无法登录
![image](https://user-images.githubusercontent.com/8335353/219960282-38d2c684-bde6-49b7-bc1b-7f3651900394.png)

![image](https://user-images.githubusercontent.com/8335353/219960334-202feb5b-a0cd-4bc6-8120-267c555e7f6f.png)

**Comment by karminski** [comment]
您好, 请问您是怎么部署的呢? 手动部署脚本里面, 密码的bcrypt hash值不是这个. 请尝试用 illa-cli (https://github.com/illacloud/illa) 部署?

https://github.com/illacloud/deploy-illa-manually/blob/a2d19fb6cf75cc5b5fd596b335641905358ea1f6/docker/postgres-init.sh#L215

**Comment by supperman009** [comment]
你发的密码是这个值啊，只是INSERT INTO是在shell里执行你转义了$符号，以防止被识别为变量。所以最终值就是我库里这个值60个字符，如果带\转义符执行，会报错，值超长
![image](https://user-images.githubusercontent.com/8335353/219990090-2da23443-7425-4974-b175-0f49a80cc081.png)

**Comment by supperman009** [comment]
我部署的docker-compose版本的，貌似是不支持root和默认password登录。改用部署docker run的。部署成功了。进去之后，界面简洁，挺好。就是有一些不足的地方：没有示例 demo example之类的，没有帮助文档或指引，只有一些基本组件，可以拖拽生成页面。生成的页面如何获取也没有说明，发布之后的确可以独立浏览，不过都是最终发布形态的。

这个项目感觉不错，继续推广吧。希望能够有更多的帮助文档、视频或者资料什么的。如果用来体验的docker套装，里面能直接带一些常见的比如单页面应用的demo，多页面应用的demo，手机端Html5的demo，PC端的demo什么的，感觉会更好一些。修修改改就能用，总好过完全从头来。

黑箱化有些严重，比如生成的app，怎么获取部署，如果有一些特殊的要求，怎么对生成的app修改？也希望有说明。整体上感觉还是很不错的！加油吧，希望成为个顶级项目！

**Comment by wenzhuo2022** [comment]
感谢建议。我们这几个月会陆续上线新用户的引导demo、应用模板；文档也以每周3～4篇的节奏补全中

**Comment by supperman009** [comment]
期待中……

**Comment by karminski** [comment]
@supperman009 请尝试试用最新的版本，我们已经更新了哈。
