### ISSUE TITLE
本地部署，初始化db这块好像出问题了。

### ISSUE THREAD

**Issue by xiaogea01** [illacloud/deploy-illa-manually#2]
09:04:07.780 UTC [200] STATEMENT:  create database illa;
2022-11-21 09:04:07.784 UTC [173] LOG:  background worker "logical replication launcher" (PID 190) exited with exit code 1
2022-11-21 09:04:07.833 UTC [182] LOG:  shutting down
2022-11-21 09:04:07.909 UTC [173] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

FATAL:  terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
connection to server was lost
2022/11/21 09:04:08 [emerg] 241#241: io_setup() failed (38: Function not implemented)
--------------------------------------------------------------

看日志，导致部分表初始化失败了。

2022-11-21 09:04:28.411 UTC [340] FATAL:  role "illa" does not exist

环境：mac studio m1
OS: Mac Os 12.6
命令行：/bin/bash ./scripts/run-official-image.sh;

**Comment by karminski** [comment]
hi, 请提供一下您的 docker 版本?  (执行下面的命令)
```bash
docker version
```
建议使用 docker 20.10 或以上版本运行, 并且使用 root 用户执行命令.

**Comment by xiaogea01** [comment]
> hi, 请提供一下您的 docker 版本? (执行下面的命令)
> 
> ```shell
> docker version
> ```
> 
> 建议使用 docker 20.10 或以上版本运行, 并且使用 root 用户执行命令.

➜  ~ docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by karminski** [comment]
@xiaogea01 是在M1 MAC运行的吗?

**Comment by xiaogea01** [comment]
> @xiaogea01 是在M1 MAC运行的吗?

mas studio 上跑的，芯片是M1 MAX，不过最近在折腾别的东西，等手上的东西告一段落，再来试试这个
