### ISSUE TITLE
Cannot delete PostgreSQL database

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [illacloud/deploy-illa-manually#7]
Running either `clean-postgres-database-file.sh` in the docker-compose directory or `docker compose down --volumes` does not properly destroy the database. How would one go about deleting the database file?

**Comment by karminski** [comment]
@Andrew-Chen-Wang Hi, the database file was mounted at ```/var/lib/illa/database/postgresql```, you can delete this folder manually. (the ```clean-postgres-database-file.sh``` do the same thing.)

And if you changed the following configs, the postgres database file will be generated in the new folder you defined. 
```
ILLA_HOME_DIR=/var/lib/illa
PG_VOLUMN=${ILLA_HOME_DIR}/database/postgresql
```
You can delete by yourself.

**Comment by karminski** [comment]
Issue closed due to no feedback over 5 days.
